version: "3.3"

services:
  app:
    container_name: clerk-assignment-prod
    image: clerk-assignment-prod-image
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV}
    ports:
      - 8080:80
