import Head from 'next/head';
import Stack from '@layouts/Stack';
import UserList, { UserListButtons } from '@modules/UserList';
import { useWindowEvent } from '@hooks/useWindowEvent';
import { useUserListPaginationStore } from '../contexts/UserListPaginationContext';
import Hint from '@components/Hint';
import ColorPicker from '@components/ColorPicker';

const useKeyboardPagination = () => {
    useWindowEvent('keydown', (e) => {
        if (e.key === 'ArrowRight') {
            useUserListPaginationStore.getState().nextPage();
        }
        if (e.key === 'ArrowLeft') {
            useUserListPaginationStore.getState().prevPage();
        }
    });
};

const HomeContent = () => {
    useKeyboardPagination();
    return (
        <Stack direction={'column'} alignItems={'center'}>
            <ColorPicker />
            <UserList />
            <UserListButtons />
        </Stack>
    );
};

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <HomeContent />
            <Hint />
        </>
    );
}
